### ----> Local <---- ###

### Get All Local.
GET http://localhost:3000/contacts


### Get Singles
GET http://localhost:3000/contacts/6676607548a988aded040a78


### Create Contact Local
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Austin",
    "lastName": "Campbell",
    "email": "cam23021@byui.edu",
    "favoriteColor": "Lilac",
    "birthday": "05/18/1997"
}


### Update Contact Local
PUT http://localhost:3000/contacts/6676607648a988aded040a7a HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bill",
    "lastName": "Gates",
    "email": "billgates@test.com",
    "favoriteColor": "Yellow",
    "birthday": "10/28/1955"
}

### Delete Contact Local
DELETE http://localhost:3000/contacts/6676607448a988aded040a77 HTTP/1.1



### ----> Production <---- ###

### Get All
GET https://cse341-2-hovd.onrender.com/contacts

### Get Single
GET https://cse341-2-hovd.onrender.com/contacts/650c5812c06bc031e32200a1

### Create Prod Contact
POST https://cse341-2-hovd.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Austin",
    "lastName": "Campbell",
    "email": "cam23021@byui.edu",
    "favoriteColor": "Lilac",
    "birthday": "05/18/1997"
}


### Update Contact production
PUT https://cse341-2-hovd.onrender.com/contacts/650c5812c06bc031e32200a1 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bill",
    "lastName": "Gates",
    "email": "billgates@test.com",
    "favoriteColor": "Yellow",
    "birthday": "10/28/1955"
}

### Delete Contact Production
DELETE https://cse341-2-hovd.onrender.com/contacts/663662dcac815af0fb1d50e4 HTTP/1.1